### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by ghost** [BattleScribe/Pre-Release#2]
```Details:

java.lang.NullPointerException
	at net.battlescribe.a.c.c.a(BattleScribe:222)
	at net.battlescribe.a.c.c.a(BattleScribe:239)
	at net.battlescribe.a.c.l(BattleScribe:269)
	at net.battlescribe.a.a.g(BattleScribe:674)
	at net.battlescribe.a.a.a(BattleScribe:777)
	at net.battlescribe.desktop.dataeditor.DataEditorFrame.ab(BattleScribe:2086)
	at net.battlescribe.desktop.dataeditor.DataEditorFrame.b(BattleScribe:3069)
	at net.battlescribe.desktop.dataeditor.DataEditorFrame.G(BattleScribe:71)
	at net.battlescribe.desktop.dataeditor.DataEditorFrame$31.actionPerformed(BattleScribe:2702)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue.access$600(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)```

```
https://github.com/BSData/horus-heresy/blob/1161b712a1214df5de67f6a5ee2260bce1269368/The%20Horus%20Heresy.gst#L47
```

**Comment by ghost** [comment]
Appears in both Mac and Windows builds. Running with debug build triggers the same exception.

**Comment by Jonskichov** [comment]
This crash is happening because the game system folder can't be found in the data folder. This means the catalogues for the game system can't be found for importing (via CatalogueLinks). Did you move the gst somewhere or move files around in the data folder?

The beta version uses it's own data folder in `BattleScribe_BETA` so maybe just copy/paste everything from the normal `BattleScribe` folder and see if it helps. The folder structure of the data folder is important for BattleScribe to be able to locate data files.

Either way, I've fixed the exception for the next release. But obviously if it can't find the game system folder, importing catalogues via CatalogueLinks is still not going to work...

**Comment by ghost** [comment]
Tried a few different scenarios. From my git checkout in my Dropbox app
folder on Mac, importing the GST on Mac (maybe this feature doesn't make
sense anymore?), and downloading from the index in the app on Windows. I
will play with it a bit more to find a workaround.

**Comment by Jonskichov** [comment]
Ultimately the folder structure is important. Remember the "root" data folder location is defined under Manage Data. Under this, there's the data folder, then each game system has it's own folder containing the gst and it's cat files. This structure is important.

Second, remember the beta has it's own folder for data and settings: `BattleScribe_BETA` so it's separate from the stable version's normal `BattleScribe` folder. By default, these folders live in your user directory (whatever that is on your platform).

You might run into problems if you're trying to open files outside of this folder structure (e.g. the gst is on your desktop or in some random folder without it's cat files).

For the beta (at least) I suggest you just stick to the standard folder layout.

Delete the `BattleScribe_BETA` folder, then launch the app to re-create it. Then, update your data (checking the delete button) or copy/paste the full data folder from the stable `BattleScribe` folder to the new `BattleScribe_BETA` folder (I don't recommend copying the settings folder over though!).

**Comment by ghost** [comment]
All my scenarios had the GST in the same directory as the RST, spare when
using the Import feature.

**Comment by ghost** [comment]
Err, I meant CAT when I typed RST.

**Comment by Jonskichov** [comment]
But was this under the `BattleScribe_BETA/data/<gst folder>` directory?

When the gst is loaded, BattleScribe needs to find the folder containing the cat files associated with the gst (so it can do imports of Catalogues via CatalogueLinks, or to present the list of available Catalogues for the Game System when creating a Roster).

To do this, it takes the ID of the Game System, then looks in the folders under `BattleScribe_BETA/data/` until it finds the one containing the gst file with that ID (a bit roundabout, but BattleScribe does not always know the particular file the gst was originally read from. Yes, there's work/improvements that can be done here, but that's another story).

This is where your crash was happening - it could not find the folder under `BattleScribe_BETA/data/` containing the gst file with the ID of the Game System you're trying to load. Which means the .gst file isn't where BattleScribe expects it to be.

**Comment by ghost** [comment]
Works with a fresh clone inside of BattleScribe_BETA/data/

**Comment by Jonskichov** [comment]
Excellent :D

(still, even in this situation it shouldn't throw a Null Pointer, so that's fixed for the next update 😄 )
